message-format:
  alert: "&c⚠ &e%s"
  invalid-args: "&c⚠ &e%1$s: &f&l参数无效: &c%2$s"
  info: "&a✿ &f%s"

version: 2
messages:
  spawn_not_valid: "你没有有效的重生点（尝试使用床或重生锚）"
  invalid_args: "参数无效"
  tps_result: "当前 TPS 为: %s"
  on: "开启"
  off: "关闭"
  switch_status: "快捷栏状态显示已"
  patrol_msg: "野生的灾厄巡逻队出现在 %1$s, %2$s, %3$s！"
  trader_msg: "野生的流浪商人出现在 %1$s, %2$s, %3$s！"
  raid_msg: "玩家 %1$s 引发了一场针对其所在村庄的袭击！"
  raid_update: "新一批敌人生成位置位于 %1$s, %2$s, %3$s（第 %4$s 批，共 %5$s 批）"
  raid_end_draw: "位于 %1$s, %2$s, %3$s 的袭击以平局告终"
  raid_end_fail: "未能抵御位于 %1$s, %2$s, %3$s 的袭击！"
  raid_end_win: "成功抵御了位于 %1$s, %2$s, %3$s 的袭击！"
  raid_end_win_pl: "%1$s 等玩家成功抵御了位于 %2$s, %3$s, %4$s 的袭击！"